# Buid BulletSim binaries from the latest Bullet and BulletSim glue sources

# https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/
# uses cmake as shell to do commands in both environments

name: BulletSim binaries

on:
  push:
    branches: 
      - workflow2

jobs:
  build:
    strategy:
      matrix: 
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: windows-latest
            name: "BulletSim binary build for Windows"
            build_type: Release
            ext: dll
            script: bat
            artif: binary-windows

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          ref: workflow2
          path: bulletsim

      - name: checkout Bullet
        uses: actions/checkout@v3
        with:
          repository: bulletphysics/bullet3
          path: bulletsim/bullet3

      - name: apply patches to Bullet
        run: |
          cd bulletsim/bullet3
          Get-ChildItem -Path ../00*.patch | ForEach-Object { git apply $_.FullName }

      - name: install CMake
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.3.1

      - name: build Bullet build files
        run: |
          cd bulletsim
          ./buildBulletCMake.${{ matrix.script }}

      - name: some debug
        run: |
          cd bulletsim/bullet3/bullet-build
          dir

      - name: build Bullet physics engine
        run: |
          cd bulletsim/bullet3/bullet-build
          dotnet build -c Release BULLET_PHYSICS.sln

      - name: more debug
        run: |
          echo "============== LIB"
          Get-ChildItem -Path bulletsim/bullet3/bullet-build/ -Filter *.lib -File -Recurse -ErrorAction SilentlyContinue | Where { ! $_.PSIsContainer } | Select Name
          echo "============== DLL"
          Get-ChildItem -Path bulletsim/bullet3/bullet-build/ -Filter *.dll -File -Recurse -ErrorAction SilentlyContinue | Where { ! $_.PSIsContainer } | Select Name
          echo "============== SO"
          Get-ChildItem -Path bulletsim/bullet3/bullet-build/ -Filter *.so -File -Recurse -ErrorAction SilentlyContinue | Where { ! $_.PSIsContainer } | Select Name

      - name: build BulletSim
        run: |
          cd bulletsim
          ./buildBulletSim.${{ matrix.script }}

      - name: Upload built image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artif }}
          path: bulletsim/*.${{ matrix.ext }}
          if-no-files-found: error

# vim: tabstop=2 shiftwidth=2 autoindent expandtab

